# Generated by Django 3.2.9 on 2021-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('year', models.PositiveSmallIntegerField(default=2000)),
                ('description', models.TextField(default='')),
                ('premiere', models.DateField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
            ],
        ),
    ]
