# Generated by Django 3.2.9 on 2021-12-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0002_alter_movie_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (5, 'Przygodowy'), (3, 'Sci-fi'), (6, 'Akcji'), (7, 'Kryminalny'), (4, 'Dramat'), (9, 'Sensacyjny'), (8, 'Romans'), (2, 'Komedia'), (0, 'Inne')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_web.additionalinfo'),
        ),
    ]
