# Generated by Django 3.2.9 on 2021-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0005_auto_20211202_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (7, 'Kryminalny'), (6, 'Akcji'), (9, 'Sensacyjny'), (5, 'Przygodowy'), (8, 'Romans'), (3, 'Sci-fi'), (4, 'Dramat'), (2, 'Komedia'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='gwiazdki',
            field=models.PositiveSmallIntegerField(choices=[(5, '*****'), (3, '***'), (4, '****'), (1, '*'), (2, '**')], default=1),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('filmy', models.ManyToManyField(to='movies_web.Movie')),
            ],
        ),
    ]
