# Generated by Django 3.2.9 on 2021-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0006_auto_20211202_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (1, 'Horror'), (7, 'Kryminalny'), (0, 'Inne'), (8, 'Romans'), (4, 'Dramat'), (6, 'Akcji'), (5, 'Przygodowy'), (9, 'Sensacyjny')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='gwiazdki',
            field=models.PositiveSmallIntegerField(choices=[(1, '*'), (5, '*****'), (3, '***'), (4, '****'), (2, '**')], default=1),
        ),
    ]
