# Generated by Django 3.2.9 on 2021-12-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0007_auto_20211202_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='filmy',
            field=models.ManyToManyField(related_name='actors', to='movies_web.Movie'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Przygodowy'), (0, 'Inne'), (6, 'Akcji'), (1, 'Horror'), (2, 'Komedia'), (7, 'Kryminalny'), (9, 'Sensacyjny'), (3, 'Sci-fi'), (8, 'Romans'), (4, 'Dramat')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='gwiazdki',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Bardzo zły'), (1, 'Zły'), (2, 'Dobry'), (3, 'Bardzo dobry')], default=1),
        ),
    ]
