# Generated by Django 3.2.9 on 2021-12-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_web', '0009_alter_additionalinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (0, 'Inne'), (6, 'Akcji'), (4, 'Dramat'), (8, 'Romans'), (5, 'Przygodowy'), (9, 'Sensacyjny'), (3, 'Sci-fi'), (1, 'Horror'), (7, 'Kryminalny')], default=0),
        ),
    ]
